### ISSUE TITLE
Don't shadow Git built-ins

### ISSUE THREAD

**Issue by ccharles** [duylam/git-gc#2]
[`git-gc`][1] already exists as part of Git. Choose another name.

[1]: https://git-scm.com/docs/git-gc

**Comment by duylam** [comment]
Thanks @ccharles . Although the name is same but the actual work is different, I will consider another name for branch cleaning-up.

**Comment by duylam** [comment]
@ccharles I've renamed the tool to `git-branch-clean` for making clean the purpose. Thanks for your feedback
