### ISSUE TITLE
Tool is prompting that it will delete branches that are still tracked remotely.

### ISSUE THREAD

**Issue by cdesserich** [duylam/git-gc#4]
My guess is that because I have multiple remotes. The tool may not support that. However, it would be nice 😃. Also, the explicit keep `-k` is not working in this scenario.

![git-branch-structure](https://user-images.githubusercontent.com/19719543/94314723-223ace80-ff4f-11ea-83b5-ca283e33df67.png)

![git-branch-clean-command-line](https://user-images.githubusercontent.com/19719543/94314743-2b2ba000-ff4f-11ea-9e36-656982ee5faf.png)

**Comment by cdesserich** [comment]
Update: I did some more testing and also realized that I didn't leave system description. It may make a difference. Windows 10, Node version 12.18.3 installed with the Windows installer (i.e. it is Program Files), Git version 2.28.0.windows.1 also installed with installer, and I'm running things in Git-bash. The machine is very locked down because it is owned by my client. I'm usually on a Mac, but cannot be for my current project.

As for the further testing I can't seem to get the `-k` flag to work at all, even with a repo that only has one remote (origin), although it did not delete the master branch...

**Comment by duylam** [comment]
> It may make a difference. Windows 10, Node version 12.18.3 installed with the Windows installer (i.e. it is Program Files), Git version 2.28.0.windows.1 also installed with installer, and I'm running things in Git-bash

@cdesserich Thanks for giving detailed env info. I guess the issue may be because the different behavior of git on WIndows or newer version. Since I don't have Windows for checking, I leave the issue there so that other people may contribute the fixing

**Comment by duylam** [comment]
Closing as staled
